### ISSUE TITLE
Cursor position shifts 1 letter to the left after the intellisense loads up the where keyword

### ISSUE THREAD

**Issue by kashif-khan** [kdcro101/vscode-cassandra#2]
**Describe the bug**
Cursor position goes haywire when typing the query after the `where` condition is chosen from the intellisense. PFA 

**To Reproduce**
1. Open a new CQL editor.
2. Choose the appropriate cluster and keyspace.
3. Write a `select `query with where a `where` condition.
4. When you type the value for the `where` condition the cursor position shifts 1 letter to the left. See the error in the gif.

**Expected behavior**
The cursor should maintain its visual and actual position in the editor.

**Screenshots**
![cassandra-workbench-bug-1](https://user-images.githubusercontent.com/661339/48213822-a3f9d100-e3a4-11e8-830d-ca4106ae6525.gif)

**System info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise 64 bit [Version 10.0.16299.611]
 - Cassandra version: 2.2.13
 - vscode version: 1.28.2 (user setup)
    - Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
    - Date: 2018-10-17T00:23:51.859Z
    - Electron: 2.0.9
    - Chrome: 61.0.3163.100
    - Node.js: 8.9.3
    - V8: 6.1.534.41
    - Architecture: x64

**Comment by kdcro101** [comment]
@kashif-khan ,

Thank you for your feedback!

I have reproduced bug you submitted. It affects windows platform only. 
I will keep you posted here.

**Comment by kdcro101** [comment]
@kashif-khan,

Please update to version `0.2.1` problem should be fixed.
Let me know how it went on your side.

Thank you again for your contribution!

**Comment by kashif-khan** [comment]
The issue has been resolved.
