### ISSUE TITLE
Unable to execute multiple SELECT statements

### ISSUE THREAD

**Issue by kashif-khan** [kdcro101/vscode-cassandra#3]
**Describe the bug**
Open a new CQL editor. Type two select queries. Select a single statement from the editor and execute. The error says it cannot execute multiple SELECT statements.

**To Reproduce**
1. Open a new CQL editor. 
2. Type two select queries.
3. Select a single statement from the editor and execute.
4. The error says it cannot execute multiple statements. 

**Expected behavior**
The editor should allow you to run the selected query from the editor.

**Screenshots**
![cassandra-workbench-bug-2](https://user-images.githubusercontent.com/661339/48215328-07d1c900-e3a8-11e8-8703-2d0a5e0ccaf4.gif)

**System info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise 64 bit [Version 10.0.16299.611]
 - Cassandra version: 2.2.13
 - vscode version: 1.28.2 (user setup)
    - Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
    - Date: 2018-10-17T00:23:51.859Z
    - Electron: 2.0.9
    - Chrome: 61.0.3163.100
    - Node.js: 8.9.3
    - V8: 6.1.534.41
    - Architecture: x64

**Comment by kdcro101** [comment]
@kashif-khan ,

Thank you for reporting! 

Execution of multiple `SELECT ` statements is disabled by design.
What results do you expect from executing multiple `SELECT` statements?

**Comment by kashif-khan** [comment]
@kdcro101 ,

In the example shown, I tried to execute a single `SELECT` statement by selecting it from the cursor for which it failed to execute. I am thinking that it should allow the user to have multiple statements in a file but only 1 can be executed at a time.

On the contrary, I would like to suggest the following features: 

- The output/results window should have tabs for multiple-statement execution.
- Alternatively, it can show groupings of results for multiple-statement execution.
