### ISSUE TITLE
Undefined Column if names are not lower-case

### ISSUE THREAD

**Issue by alexandermikuta** [kdcro101/vscode-cassandra#5]
**Describe the bug**
Cassandra uses lower-case as default. If non-lower-case names should be preserved they need to be quoted.

**To Reproduce**
1. Create a table with e.g. column name "userId"
2. Select table via cassandra-workbench
3 Message "undefined column name userId" appears as workbench selects without quotes around column-name

**Expected behavior**
Select should work also for non-lower-case names, so selects from workbench should be quoted.

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Cassandra version: 3.11.3
 - vscode version: 1.29.1

**Comment by kdcro101** [comment]
@alexandermikuta,

Thank you for your feedback!
Please update to version `0.3.5`. Problem should be fixed.

If you have any problems open issue.

**Comment by alexandermikuta** [comment]
Thanks for your quick fix. The Column-Names are fixed now, but the problem seems also to exist for Table-Names. There I get still the same problem.

Kind regards,
Alex

**Comment by kdcro101** [comment]
@alexandermikuta ,

Thank you for your feedback.
Please update to version `0.3.6`. All object names are double-quoted if case sensitive.

If you have any problems, please open **`new`** issue.
